export const words = () => {
    return [
        [
            "amount",
            "количество",
            "images/amount.jpg",
            "sounds/amount.mp3"
          ],
          [
            "argument",
            "аргумент",
            "images/argument.jpg",
            "sounds/argument.mp3"
          ],
          [
            "art",
            "искусство",
            "images/art.jpg",
            "sounds/art.mp3"
          ],
          [
            "be",
            "быть",
            "images/be.jpg",
            "sounds/be.mp3"
          ],
          [
            "beautiful",
            "красивый",
            "images/beautiful.jpg",
            "sounds/beautiful.mp3"
          ],
          [
            "belief",
            "вера",
            "images/belief.jpg",
            "sounds/belief.mp3"
          ],
          [
            "cause",
            "причина",
            "images/cause.jpg",
            "sounds/cause.mp3"
          ],
          [
            "certain",
            "определенный",
            "images/certain.jpg",
            "sounds/certain.mp3"
          ],
          [
            "chance",
            "шанс",
            "images/chance.jpg",
            "sounds/chance.mp3"
          ],
          [
            "change",
            "изменять",
            "images/change.jpg",
            "sounds/change.mp3"
          ],
          [
            "clear",
            "прозрачный",
            "images/clear.jpg",
            "sounds/clear.mp3"
          ],
          [
            "common",
            "общий",
            "images/common.jpg",
            "sounds/common.mp3"
          ],
          [
            "comparison",
            "сравнение",
            "images/comparison.jpg",
            "sounds/comparison.mp3"
          ],
          [
            "condition",
            "состояние",
            "images/condition.jpg",
            "sounds/condition.mp3"
          ],
          [
            "connection",
            "связь",
            "images/connection.jpg",
            "sounds/connection.mp3"
          ],
          [
            "copy",
            "копия",
            "images/copy.jpg",
            "sounds/copy.mp3"
          ],
          [
            "decision",
            "решение",
            "images/decision.jpg",
            "sounds/decision.mp3"
          ],
          [
            "degree",
            "степень",
            "images/degree.jpg",
            "sounds/degree.mp3"
          ],
          [
            "desire",
            "желание",
            "images/desire.jpg",
            "sounds/desire.mp3"
          ],
          [
            "development",
            "разработка",
            "images/development.jpg",
            "sounds/development.mp3"
          ],
          [
            "different",
            "другой",
            "images/different.jpg",
            "sounds/different.mp3"
          ],
          [
            "do",
            "делать",
            "images/do.jpg",
            "sounds/do.mp3"
          ],
          [
            "education",
            "образование",
            "images/education.jpg",
            "sounds/education.mp3"
          ],
          [
            "end",
            "конец",
            "images/end.jpg",
            "sounds/end.mp3"
          ],
          [
            "event",
            "событие",
            "images/event.jpg",
            "sounds/event.mp3"
          ]
    ];
};
